### ISSUE TITLE
Create S3 bucket for PDF uploads

### ISSUE THREAD

**Issue by dstillman** [zotero/recognizer-server#5]
We should update the SAM template to create a bucket and add a lifecycle policy for 1-day expiration:

```yaml
  UploadBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: {{ upload_bucket_name }}
      BucketEncryption: 
        ServerSideEncryptionConfiguration:
        - ServerSideEncryptionByDefault:
            SSEAlgorithm: AES256
      LifecycleConfiguration:
        Rules:
          - Id: Purge After 1 Day
            ExpirationInDays: 1
            Status: Enabled
```

And then give the lambda the `S3ReadPolicy` on that bucket.

We also need to give the translation-server lambda the `s3:PutObject` and `s3:DeleteObject` permissions, so we should [export](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/using-cfn-stack-exports.html) the bucket from this template, import it into the t-s template, and add an IAM policy document to the t-s lambda's `Policies` with those permissions (which I think we can do instead of creating an explicit IAM role). We don't want to use the SAM `S3CrudPolicy` because we don't really want t-s to be able to list the bucket or retrieve other uploads.
